Fix Static Access
pear/Date pull request #4
Opened 2018-09-19 18:57 UTC by flintweather

Update deprications: constructors, new class assign by reference
http://php.net/manual/en/language.oop5.decon.php
http://php.net/manual/en/language.operators.assignment.php
Update unit tests and package.xml for release 1.5.0a5

vendor/bin/phpunit tests
PHPUnit 3.7.38 by Sebastian Bergmann.
..........................................................
Time: 5.07 seconds, Memory: 24.75MB
OK (58 tests, 106 assertions)

2018-12-09 05:28 UTC, peter279k commented on .gitignore
> +run-tests.log
This file misses the end of file.

2018-12-09 05:33 UTC, peter279k requested changes
I write some comments for this PR and I think these comments should be concerned.

2018-12-09 05:33 UTC, peter279k commented on Date.php
> +    function __construct($date = null, $options = null)
This should add the `public` to let developer know this constructor is `public`.

2018-12-09 05:33 UTC, peter279k commented on Date.php
>      function getDate($format = DATE_FORMAT_ISO)
This method should add the `public` or `private` to let developers know the method property.

2018-12-09 05:33 UTC, peter279k commented on Date.php
> +    static function inEquivalentTimeZones($po_date1, $po_date2)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date.php
> +    static function compare($od1, $od2)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date.php
> +    static function _addOffset($pn_offset,
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Human.php
> +    static function gregorianToHuman($day = 0, $month = 0, $year = 0)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Human.php
> +    static function humanToGregorian($day, $month, $year = 0)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    function __construct($time = 0, $format = null)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    static function compare($time1, $time2)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    static function setDefaultInputFormat($format)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    static function getDefaultInputFormat()
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    static function setDefaultFormat($format)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/Span.php
> +    static function getDefaultFormat()
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/TimeZone.php
> +    function __construct($ps_id)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/TimeZone.php
> +    static function getDefault()
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/TimeZone.php
> +    static function setDefault($id)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on Date/TimeZone.php
> +    static function isValidID($ps_id)
It's the same problem and the solution I mention in the previous comment thread.

2018-12-09 05:33 UTC, peter279k commented on composer.json
>  }
It misses the end of file.

2018-12-09 05:33 UTC, peter279k commented on tests/DateSpanTest.php
>      function setUp() {
It's the same problem and the solution I mention in the previous comment thread.

2019-02-07 16:32 UTC, bpablo commented
I keep getting the following warnings that seem to be related to these changes:

Deprecated: Non-static method Date_TimeZone::isValidID() should not be called statically in /usr/share/php/Date/TimeZone.php on line 4717

This is true of several methods, but all the errors are similar.

2022-11-28 07:22 UTC, stevecharon commented
just tried a view of that static declaratoins on a really dotproject page
and it worked fine.
Had to rename a function with the name dateDiff in a file outside PEAR/Date because something thought it would be a good idea to make a dirty hack instead of fixing things.
@bpablo perhaps the same happened on your go?

2026-02-01 21:49 UTC, ashnazg commented
Package unmaintained.

2026-02-01 21:49 UTC, closed without merging